### ISSUE TITLE
Example UI

### ISSUE THREAD

**Issue by albevt** [schwartzie/weather-joan#1]
Hi  schwartzie,
i follow your readme, have a difficult to build a correctly work web interface file, but i trust in this project! It's possible to share with our a little example of the ui file?
Thank's

**Comment by schwartzie** [comment]
Hi @albevt -- thank you for your interest in this project 😀

Over the years, my UI has diverged a lot from this example, and is a little convoluted to be helpful as a learning tool for the more general goals of this project.

Where are you having trouble? I'd be happy to help you find some materials that get you on the right track. Feel free to post any code/config samples that are giving you trouble.
